### ISSUE TITLE
FullMath.sol error

### ISSUE THREAD

**Issue by wildmolasses** [blueberrynetwork/blueberry_swap#1]
@mds1 and I were taking a look at uniswap v2-related contracts that have been updated for solidity ^0.8.0. We think we found a bug in your FullMath.sol upgrade:

`fulDiv`'s `pow2` should be `d & type(uint256).max - d + 1`

Also recommend checking line 20 for the same.

Let us know if this helps, or if we were mistaken! 👍

**Comment by blueberrynetwork** [comment]
Many thanks and fixed.
